// src/components/landing/Footer.tsx
import iconFooterLogo from "@/assets/icons/icon-footer-logo.svg";
import iconEmail from "@/assets/icons/icon-email.svg";
import iconLocation from "@/assets/icons/icon-location.svg";
import iconSocial1 from "@/assets/icons/icon-social-1.svg";
import iconSocial2 from "@/assets/icons/icon-social-2.svg";
import iconSocial3 from "@/assets/icons/icon-social-3.svg";

export default function Footer() {
  const quickLinks = [
    { label: "Services", href: "#services" },
    { label: "Packages", href: "#packages" },
    { label: "Why Choose Us", href: "#why-us" },
    { label: "FAQ", href: "#faq" },
    { label: "Book Appointment", href: "#" },
    { label: "Apply to Groomer", href: "#" },
  ];

  const supportLinks = [
    { label: "Help Center", href: "#" },
    { label: "Contact Us", href: "#contact" },
    { label: "Cancellation Policy", href: "#" },
    { label: "Service Areas", href: "#" },
    { label: "Customer Reviews", href: "#" },
    { label: "Pet Care Blog", href: "#" },
  ];

  return (
    <footer className="bg-[#8b6357] w-full" data-name="Footer">
      <div className="flex flex-col items-center w-full">
        <div className="max-w-7xl w-full px-[28px] md:px-[36px] py-[28px]">
          <div className="content-stretch flex flex-col gap-[24px] items-center w-full">
            {/* Main Content */}
            <div className="content-center flex flex-wrap gap-[24px] items-center md:items-start w-full">
              {/* Brand Column */}
              <div className="basis-0 content-stretch flex flex-col gap-[14px] grow items-start min-w-[272px] w-full md:w-auto">
                {/* Logo and Name */}
                <div className="content-stretch flex gap-[10.5px] items-center w-full">
                  <div className="h-[35px] relative shrink-0 w-[31px]">
                    <img
                      src={iconFooterLogo}
                      alt="Logo"
                      className="block size-full"
                    />
                  </div>
                  <h3 className="font-['Comfortaa:Bold',_sans-serif] font-bold leading-[28px] text-white text-[21px]">
                    Mutopia
                  </h3>
                </div>

                {/* Description */}
                <p className="font-['Comfortaa:Regular',_sans-serif] font-normal leading-[22.75px] text-[14px] text-white w-[224px] whitespace-pre-wrap">
                  Premium pet grooming services bringing professional care
                  directly to your door. Your pet's comfort is our priority.
                </p>

                {/* Email */}
                <div className="content-stretch flex gap-[10.5px] items-center w-full">
                  <div className="relative shrink-0 size-[16px]">
                    <img
                      src={iconEmail}
                      alt="Email"
                      className="block size-full"
                    />
                  </div>
                  <p className="font-['Comfortaa:Regular',_sans-serif] font-normal leading-[21px] text-[14px] text-white">
                    hello@mutopia.ca
                  </p>
                </div>

                {/* Location */}
                <div className="content-stretch flex gap-[10.5px] items-center w-full max-w-[273px]">
                  <div className="relative shrink-0 size-[16px]">
                    <img
                      src={iconLocation}
                      alt="Location"
                      className="block size-full"
                    />
                  </div>
                  <p className="font-['Comfortaa:Regular',_sans-serif] font-normal leading-[21px] text-[14px] text-white">
                    Serving Greater Vancouver Area
                  </p>
                </div>
              </div>

              {/* Quick Links Column - Desktop only */}
              <div className="hidden lg:flex basis-0 content-stretch flex-col gap-[21px] grow items-start min-h-px min-w-px">
                <h4 className="font-['Comfortaa:Medium',_sans-serif] font-medium leading-[21px] text-[14px] text-white">
                  Quick Links
                </h4>
                <div className="content-stretch flex flex-col gap-[10.5px] items-start w-full">
                  {quickLinks.map((link, index) => (
                    <a
                      key={index}
                      href={link.href}
                      className="font-['Comfortaa:Regular',_sans-serif] font-normal leading-[21px] text-[14px] text-white hover:text-[#de6a07] transition-colors duration-200 cursor-pointer"
                    >
                      {link.label}
                    </a>
                  ))}
                </div>
              </div>

              {/* Support Column - Desktop only */}
              <div className="hidden lg:flex basis-0 content-stretch flex-col gap-[21px] grow items-start min-h-px min-w-px">
                <h4 className="font-['Comfortaa:Medium',_sans-serif] font-medium leading-[21px] text-[14px] text-white">
                  Support
                </h4>
                <div className="content-stretch flex flex-col gap-[10.5px] items-start w-full">
                  {supportLinks.map((link, index) => (
                    <a
                      key={index}
                      href={link.href}
                      className="font-['Comfortaa:Regular',_sans-serif] font-normal leading-[21px] text-[14px] text-white hover:text-[#de6a07] transition-colors duration-200 cursor-pointer"
                    >
                      {link.label}
                    </a>
                  ))}
                </div>
              </div>

              {/* Follow Us Column */}
              <div className="content-stretch flex flex-col gap-[21px] items-start shrink-0 w-full md:w-auto">
                <div className="content-stretch flex flex-col gap-[14px] items-start w-[133px]">
                  <h4 className="font-['Comfortaa:Medium',_sans-serif] font-medium leading-[21px] text-[14px] text-white">
                    Follow Us
                  </h4>
                  <div className="content-stretch flex gap-[14px] items-start w-full">
                    {/* Facebook */}
                    <a
                      href="#"
                      className="bg-[#de6a07] rounded-full size-[35px] flex items-center justify-center hover:bg-[rgba(222,106,7,0.8)] transition-colors duration-200 cursor-pointer relative shrink-0"
                      aria-label="Facebook"
                    >
                      <div className="relative shrink-0 size-[20px]">
                        <img
                          src={iconSocial1}
                          alt="Facebook"
                          className="block size-full"
                        />
                      </div>
                    </a>

                    {/* Instagram */}
                    <a
                      href="#"
                      className="bg-[#de6a07] rounded-full size-[35px] flex items-center justify-center hover:bg-[rgba(222,106,7,0.8)] transition-colors duration-200 cursor-pointer relative shrink-0"
                      aria-label="Instagram"
                    >
                      <div className="relative shrink-0 size-[20px]">
                        <img
                          src={iconSocial2}
                          alt="Instagram"
                          className="block size-full"
                        />
                      </div>
                    </a>

                    {/* Twitter */}
                    <a
                      href="#"
                      className="bg-[#de6a07] rounded-full size-[35px] flex items-center justify-center hover:bg-[rgba(222,106,7,0.8)] transition-colors duration-200 cursor-pointer relative shrink-0"
                      aria-label="Twitter"
                    >
                      <div className="relative shrink-0 size-[20px]">
                        <img
                          src={iconSocial3}
                          alt="Twitter"
                          className="block size-full"
                        />
                      </div>
                    </a>
                  </div>
                </div>
              </div>
            </div>

            {/* Divider */}
            <div className="bg-[#fff9ec] h-px shrink-0 w-full" />

            {/* Bottom Footer: Copyright + Policy Links */}
            <div className="content-center flex flex-col md:flex-row flex-wrap gap-[24px] items-center md:items-start justify-center md:justify-between w-full">
              <p className="flex-[1_0_0] font-['Comfortaa:Regular',_sans-serif] font-normal min-h-px min-w-px leading-[17.5px] text-[12.25px] text-center md:text-left text-white whitespace-pre-wrap order-1 md:order-1">
                © 2026 Mutopia. All rights reserved.
              </p>
              <div className="h-[17.5px] relative shrink-0 order-2 md:order-2">
                <div className="content-stretch flex font-['Comfortaa:Regular',_sans-serif] font-normal gap-[24px] h-[17.5px] items-start leading-[17.5px] text-[12.25px] text-white">
                  <a
                    href="#"
                    className="relative shrink-0 hover:text-[#de6a07] transition-colors duration-200 cursor-pointer"
                  >
                    Privacy Policy
                  </a>
                  <a
                    href="#"
                    className="relative shrink-0 hover:text-[#de6a07] transition-colors duration-200 cursor-pointer"
                  >
                    Terms of Service
                  </a>
                  <a
                    href="#"
                    className="relative shrink-0 hover:text-[#de6a07] transition-colors duration-200 cursor-pointer"
                  >
                    Cookie Policy
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </footer>
  );
}

// src/components/Footer.vue
<script setup lang="ts">
// Button、Input、Separator、Facebook、Instagram、Twitter、Mail、MapPin 都自动可用
</script>

<template>
  <footer id="contact" class="bg-secondary text-white">
    <!-- Newsletter Section -->
    <div class="bg-primary py-16 rounded-t-[3rem] relative overflow-hidden">
      <!-- Curved background elements -->
      <div class="absolute inset-0">
        <div class="absolute top-0 -right-20 w-40 h-40 bg-white/10 rounded-full blur-2xl"></div>
        <div
          class="absolute bottom-0 -left-20 w-60 h-60 bg-secondary/20 rounded-full blur-3xl"
        ></div>
      </div>
      <div class="relative max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center z-10">
        <h3 class="text-2xl font-bold mb-4">Stay Updated with Pet Care Tips</h3>
        <p class="text-primary-foreground/90 mb-8 max-w-2xl mx-auto">
          Get expert grooming tips, seasonal care advice, and exclusive offers delivered to your
          inbox.
        </p>
        <div class="flex flex-col sm:flex-row gap-4 max-w-md mx-auto">
          <Input
            placeholder="Enter your email"
            class="bg-white text-gray-900 border-0 rounded-full"
          />
          <Button
            variant="secondary"
            class="whitespace-nowrap bg-white text-primary hover:bg-gray-100 rounded-full"
          >
            Subscribe
          </Button>
        </div>
      </div>
    </div>

    <!-- Main Footer -->
    <div class="py-16">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
          <!-- Company Info -->
          <div class="space-y-6">
            <div class="flex items-center space-x-3 mb-4">
              <img src="@/assets/images/mutopia-logo.png" alt="Mutopia Logo" class="h-10 w-10" />
              <h3 class="text-2xl font-bold">Mutopia</h3>
            </div>
            <div>
              <p class="text-gray-400 leading-relaxed">
                Premium mobile pet grooming services bringing professional care directly to your
                door. Your pet's comfort is our priority.
              </p>
            </div>

            <div class="space-y-3">
              <div class="flex items-center gap-3">
                <Mail :size="16" class="text-primary" />
                <span>hello@mutopia.ca</span>
              </div>
              <div class="flex items-center gap-3">
                <MapPin :size="16" class="text-primary" />
                <span>Serving Greater Toronto Area</span>
              </div>
            </div>
          </div>

          <!-- Quick Links -->
          <div>
            <h4 class="font-semibold mb-6">Quick Links</h4>
            <ul class="space-y-3">
              <li>
                <a href="#services" class="text-gray-400 hover:text-white transition-colors">
                  Services
                </a>
              </li>
              <li>
                <a href="#packages" class="text-gray-400 hover:text-white transition-colors">
                  Packages
                </a>
              </li>
              <li>
                <a href="#why-us" class="text-gray-400 hover:text-white transition-colors">
                  Why Choose Us
                </a>
              </li>
              <li>
                <a href="#faq" class="text-gray-400 hover:text-white transition-colors">FAQ</a>
              </li>
              <li>
                <a href="/booking" class="text-gray-400 hover:text-white transition-colors">
                  Book Appointment
                </a>
              </li>
              <li>
                <a href="/careers" class="text-gray-400 hover:text-white transition-colors">
                  Apply to Groomer
                </a>
              </li>
            </ul>
          </div>

          <!-- Support -->
          <div>
            <h4 class="font-semibold mb-6">Support</h4>
            <ul class="space-y-3">
              <li>
                <a href="/help" class="text-gray-400 hover:text-white transition-colors">
                  Help Center
                </a>
              </li>
              <li>
                <a href="/contact" class="text-gray-400 hover:text-white transition-colors">
                  Contact Us
                </a>
              </li>
              <li>
                <a href="/cancellation" class="text-gray-400 hover:text-white transition-colors">
                  Cancellation Policy
                </a>
              </li>
              <li>
                <a href="/service-areas" class="text-gray-400 hover:text-white transition-colors">
                  Service Areas
                </a>
              </li>
              <li>
                <a href="/testimonials" class="text-gray-400 hover:text-white transition-colors">
                  Customer Reviews
                </a>
              </li>
              <li>
                <a href="/blog" class="text-gray-400 hover:text-white transition-colors">
                  Pet Care Blog
                </a>
              </li>
            </ul>
          </div>

          <!-- Business Hours & Social -->
          <div>
            <h4 class="font-semibold mb-6">Business Hours</h4>
            <div class="space-y-2 mb-6">
              <div class="flex justify-between text-sm">
                <span class="text-gray-400">Monday - Friday</span>
                <span>8:00 AM - 6:00 PM</span>
              </div>
              <div class="flex justify-between text-sm">
                <span class="text-gray-400">Saturday</span>
                <span>9:00 AM - 5:00 PM</span>
              </div>
              <div class="flex justify-between text-sm">
                <span class="text-gray-400">Sunday</span>
                <span>10:00 AM - 4:00 PM</span>
              </div>
            </div>

            <div>
              <h5 class="font-medium mb-4">Follow Us</h5>
              <div class="flex gap-4">
                <a
                  href="#"
                  class="w-10 h-10 bg-gray-800 rounded-full flex items-center justify-center hover:bg-primary transition-colors"
                >
                  <Facebook :size="20" />
                </a>
                <a
                  href="#"
                  class="w-10 h-10 bg-gray-800 rounded-full flex items-center justify-center hover:bg-primary transition-colors"
                >
                  <Instagram :size="20" />
                </a>
                <a
                  href="#"
                  class="w-10 h-10 bg-gray-800 rounded-full flex items-center justify-center hover:bg-primary transition-colors"
                >
                  <Twitter :size="20" />
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <Separator class="bg-gray-800" />

    <!-- Bottom Footer -->
    <div class="py-6">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex flex-col md:flex-row justify-between items-center gap-4">
          <p class="text-gray-400 text-sm">© 2024 Mutopia. All rights reserved.</p>
          <div class="flex gap-6 text-sm">
            <a href="/privacy" class="text-gray-400 hover:text-white transition-colors">
              Privacy Policy
            </a>
            <a href="/terms" class="text-gray-400 hover:text-white transition-colors">
              Terms of Service
            </a>
            <a href="/cookies" class="text-gray-400 hover:text-white transition-colors">
              Cookie Policy
            </a>
          </div>
        </div>
      </div>
    </div>
  </footer>
</template>
