// components/Services.tsx
import { useState } from "react";
// import svgPaths from "../imports/svg-aj6ul1v84s";
import { Card, CardContent } from "./ui/card";
import { Badge } from "./ui/badge";
import { Button } from "./ui/button";
import { OrangeButton } from "./OrangeButton";
import {
  Clock,
  Droplets,
  Scissors,
  Sparkles,
  ArrowRight,
} from "lucide-react";
import {
  Carousel,
  CarouselContent,
  CarouselItem,
} from "./ui/carousel";

// Service Card Component
interface ServiceCardProps {
  icon: React.ReactNode;
  title: string;
  description: string;
  duration: string;
  price: string;
  includes: string[];
  isPopular?: boolean;
  onBookClick?: () => void;
  isMobile?: boolean;
}

function ServiceCard({
  icon,
  title,
  description,
  duration,
  price,
  includes,
  isPopular = false,
  onBookClick,
  isMobile = false,
}: ServiceCardProps) {
  return (
    <div className="relative pt-4 h-full">
      {isPopular && (
        <Badge className="absolute bg-[#de6a07] left-[24.5px] top-0 h-[24px] px-[16px] py-[4px] rounded-[12px] hover:bg-[#de6a07] z-10 whitespace-nowrap">
          <p className="font-['Comfortaa:Medium',_sans-serif] font-medium leading-[14px] text-[10px] text-white whitespace-nowrap">
            Most Popular
          </p>
        </Badge>
      )}
      <Card
        className={`relative bg-white rounded-[21px] border-2 border-[rgba(0,0,0,0.1)] p-0 h-full ${isMobile ? "w-[280px]" : "w-[336px]"}`}
      >
        <CardContent
          className={`flex flex-col gap-[20px] items-center h-full ${isMobile ? "p-[20px]" : "p-[30px]"}`}
        >
          <div className="content-stretch flex flex-col gap-[32px] items-center w-full flex-1">
            {/* Header */}
            <div className="content-stretch flex flex-col gap-[20px] items-center w-full">
              <div className="bg-[rgba(222,106,7,0.1)] rounded-[21px] size-[56px] flex items-center justify-center">
                {icon}
              </div>

              <div className="content-stretch flex flex-col gap-[12px] items-start w-full">
                <h3 className="font-['Comfortaa:Regular',_sans-serif] font-normal leading-[28px] text-[#4a3c2a] text-[16px] text-center w-full">
                  {title}
                </h3>
                <p className="font-['Comfortaa:Regular',_sans-serif] font-normal leading-[22.75px] text-[14px] text-[rgba(74,60,42,0.7)] text-center w-full">
                  {description}
                </p>
              </div>
            </div>

            {/* Pricing */}
            <div className="content-stretch flex flex-col gap-[16px] items-start w-full">
              <div className="content-stretch flex h-[24.5px] items-center justify-between w-full">
                <div className="flex gap-[7px] items-center">
                  <Clock
                    className="size-[16px] text-[#DE6A07] opacity-60"
                    strokeWidth={1.33}
                  />
                  <p className="font-['Comfortaa:Regular',_sans-serif] font-normal leading-[17.5px] text-[12.25px] text-[rgba(74,60,42,0.6)]">
                    {duration}
                  </p>
                </div>
                <div>
                  <p className="font-['Comfortaa:SemiBold',_sans-serif] font-semibold leading-[24.5px] text-[#de6a07]">
                    <span className="text-[14px]">From</span>
                    <span className="text-[17.5px]"> </span>
                    <span className="text-[24px]">{price}</span>
                  </p>
                </div>
              </div>

              {/* Includes */}
              <div className="content-stretch flex flex-col gap-[7px] items-start w-full">
                <p className="font-['Comfortaa:Medium',_sans-serif] font-medium leading-[21px] text-[#4a3c2a] text-[14px]">
                  Includes:
                </p>
                <div className="content-stretch flex flex-col gap-[3.5px] items-start w-full">
                  {includes.map((item, index) => (
                    <div
                      key={index}
                      className="h-[17.5px] relative w-full"
                    >
                      <div className="absolute bg-[#de6a07] left-0 rounded-full size-[5.25px] top-[6.13px]" />
                      <p className="absolute font-['Comfortaa:Regular',_sans-serif] font-normal leading-[17.5px] left-[12.25px] text-[12.25px] text-[rgba(74,60,42,0.7)] top-[-0.5px]">
                        {item}
                      </p>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>

          {/* Book Button */}
          <OrangeButton
            variant={isPopular ? "primary" : "outline"}
            size="medium"
            fullWidth
            onClick={onBookClick}
          >
            <div className="flex gap-[4px] items-center">
              <p
                className={`font-['Comfortaa:Medium',_sans-serif] font-medium leading-[17.5px] text-[14px] ${
                  isPopular ? "text-white" : "text-[#de6a07]"
                }`}
              >
                Book Now
              </p>
              <ArrowRight
                className="size-[14px]"
                stroke={isPopular ? "white" : "#DE6A07"}
                strokeWidth={2}
              />
            </div>
          </OrangeButton>
        </CardContent>
      </Card>
    </div>
  );
}

// Additional Service Item Component
interface AdditionalServiceProps {
  name: string;
  price: string;
}

function AdditionalServiceItem({
  name,
  price,
}: AdditionalServiceProps) {
  return (
    <div className="box-border flex h-[51px] items-center justify-between px-[15px] py-px rounded-[14px] w-full bg-white border border-[#E5E7EB]">
      <div className="flex gap-[10.5px] items-center min-w-0">
        <Sparkles
          className="size-[20px] text-[#DE6A07]"
          strokeWidth={1.66667}
        />
        <p className="font-['Comfortaa:Medium',_sans-serif] font-medium leading-[21px] text-[#4a3c2a] text-[14px] truncate">
          {name}
        </p>
      </div>
      <p className="font-['Comfortaa:SemiBold',_sans-serif] font-semibold leading-[21px] text-[#de6a07] text-[14px] shrink-0 ml-2">
        {price}
      </p>
    </div>
  );
}

export default function Services() {
  const [showAllServicesMobile, setShowAllServicesMobile] =
    useState(false);

  const services = [
    {
      icon: (
        <Droplets
          className="size-[32px] text-[#DE6A07]"
          strokeWidth={2.66667}
        />
      ),
      title: "Bath & Brush",
      description:
        "Refreshing bath with premium products and thorough brushing",
      duration: "1 hour",
      price: "$65",
      includes: [
        "Premium shampoo",
        "Conditioning",
        "Thorough brushing",
        "Basic nail trim",
        "Ear check",
      ],
    },
    {
      icon: (
        <Scissors
          className="size-[32px] text-[#DE6A07]"
          strokeWidth={2.66667}
        />
      ),
      title: "Full Grooming",
      description:
        "Complete wash, cut, nail trim, and styling for your pet",
      duration: "1.5-2 hours",
      price: "$95",
      includes: [
        "Bath & dry",
        "Haircut & styling",
        "Nail trimming",
        "Ear cleaning",
        "Teeth brushing",
      ],
      isPopular: true,
    },
    {
      icon: (
        <Sparkles
          className="size-[32px] text-[#DE6A07]"
          strokeWidth={2.66667}
        />
      ),
      title: "Express Groom",
      description:
        "Quick touch-up for pets who need a fast refresh",
      duration: "1 hour",
      price: "$75",
      includes: [
        "Quick wash & dry",
        "Brush out",
        "Nail trim",
        "Sanitary trim",
        "Face & feet groom",
      ],
    },
  ];

  const additionalServices = [
    { name: "Nail Painting", price: "$15" },
    { name: "Teeth Cleaning", price: "$25" },
    { name: "Flea Treatment", price: "$30" },
    { name: "De-shedding Treatment", price: "$35" },
    { name: "Aromatherapy Add-on", price: "$20" },
    { name: "Premium Cologne", price: "$10" },
  ];

  // Get services to display based on state
  // Desktop: show all, Mobile: show based on toggle state
  const displayedServicesMobile = showAllServicesMobile
    ? additionalServices
    : additionalServices.slice(0, 3);

  return (
    <div
      id="services"
      className="bg-[#fdf8f0] relative w-full py-[56px] lg:py-[56px]"
      data-name="Services"
    >
      <div className="flex flex-col gap-[56px] lg:px-14 w-full">
        {/* Title Section - Centered with max-width */}
        <div className="max-w-7xl mx-auto px-4 sm:px-8 md:px-12 lg:px-[57.5px] w-full">
          <div className="content-stretch flex flex-col gap-[12px] items-center w-full">
            <p className="font-['Comfortaa:Bold',_sans-serif] leading-[40px] text-[#4a3c2a] text-[32px] text-center">
              Our Premium Services
            </p>
            <div className="max-w-[672px] mx-auto">
              <p className="font-['Comfortaa:Regular',_sans-serif] font-normal leading-[28px] text-[16px] text-[rgba(74,60,42,0.7)] text-center">
                From basic baths to full spa treatments, we
                offer everything your pet needs to look and feel
                their absolute best.
              </p>
            </div>
          </div>
        </div>

        {/* Desktop View - Hidden on mobile */}
        <div className="hidden sm:flex content-start flex-wrap gap-[24px] items-stretch justify-center w-full max-w-7xl mx-auto px-8 md:px-12 lg:px-[57.5px]">
          {services.map((service, index) => (
            <ServiceCard
              key={index}
              {...service}
              isMobile={false}
            />
          ))}
        </div>

        {/* Mobile View - Carousel */}
        <div className="block sm:hidden w-full pb-6">
          <Carousel
            opts={{
              align: "start",
              loop: false,
            }}
            className="w-full"
          >
            <CarouselContent className="items-stretch gap-6 ml-0 pl-4">
              {services.map((service, index) => (
                <CarouselItem
                  key={index}
                  className="pl-0 basis-[280px]"
                >
                  <ServiceCard {...service} isMobile={true} />
                </CarouselItem>
              ))}
              {/* Spacer for right padding - 16px */}
              <div
                className="shrink-0 w-[16px]"
                aria-hidden="true"
              />
            </CarouselContent>
          </Carousel>
        </div>

        {/* Additional Services - Full width, no margins */}
        <div className="w-full">
          <div className="bg-white relative w-full border border-[1px] border-[#de6a07] rounded-xl">
            <div className="flex flex-col items-center w-full py-[24px] px-0 sm:px-[24px]">
              <div className="flex flex-col gap-[28px] items-center w-full">
                {/* Additional Services Title */}
                <div className="flex flex-col gap-[7px] items-center text-center max-w-[493px] mx-auto px-4 sm:px-0">
                  <p className="font-['Comfortaa:Bold',_sans-serif] leading-[28px] text-[#4a3c2a] text-[21px]">
                    Additional Services
                  </p>
                  <p className="font-['Comfortaa:Regular',_sans-serif] font-normal leading-[21px] text-[14px] text-[rgba(74,60,42,0.7)]">
                    Enhance your pet's grooming experience with
                    our premium add-ons
                  </p>
                </div>

                {/* Additional Services Grid - Desktop: show all, 3 columns */}
                <div className="hidden sm:grid grid-cols-3 gap-[20px] w-full max-w-7xl mx-auto px-[56px]">
                  {additionalServices.map((service, index) => (
                    <AdditionalServiceItem
                      key={index}
                      {...service}
                    />
                  ))}
                </div>

                {/* Additional Services Grid - Mobile: show with toggle, full width */}
                <div className="flex sm:hidden flex-col gap-[20px] w-full px-0">
                  {displayedServicesMobile.map(
                    (service, index) => (
                      <AdditionalServiceItem
                        key={index}
                        {...service}
                      />
                    ),
                  )}
                </div>

                {/* View All Button - Mobile only */}
                <Button
                  variant="outline"
                  className="sm:hidden h-[28px] rounded-[32px] w-[209px] border-2 border-[#8b6357] hover:bg-[#8b6357]/5"
                  onClick={() =>
                    setShowAllServicesMobile(
                      !showAllServicesMobile,
                    )
                  }
                >
                  <p className="font-['Comfortaa:Medium',_sans-serif] font-medium leading-[17.5px] text-[#8b6357] text-[12px]">
                    {showAllServicesMobile
                      ? "Show Less"
                      : "View All Services & Pricing"}
                  </p>
                </Button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

// src/components/Services.vue
<script setup lang="ts">
import Button from './ui/button.vue';
import Card from './ui/card.vue';
import CardContent from './ui/CardContent.vue';
import CardDescription from './ui/CardDescription.vue';
import CardFooter from './ui/CardFooter.vue';
import CardHeader from './ui/CardHeader.vue';
import CardTitle from './ui/CardTitle.vue';
import Badge from './ui/badge.vue';
import { Scissors, Droplets, Brush, Sparkles, Clock, ArrowRight } from 'lucide-vue-next';

const mainServices = [
  {
    icon: Scissors,
    title: 'Full Grooming',
    description: 'Complete wash, cut, nail trim, and styling for your pet',
    duration: '2-3 hours',
    price: 'From $80',
    features: [
      'Bath & dry',
      'Haircut & styling',
      'Nail trimming',
      'Ear cleaning',
      'Teeth brushing',
    ],
    popular: true,
  },
  {
    icon: Droplets,
    title: 'Bath & Brush',
    description: 'Refreshing bath with premium products and thorough brushing',
    duration: '1-2 hours',
    price: 'From $45',
    features: [
      'Premium shampoo',
      'Conditioning',
      'Thorough brushing',
      'Basic nail trim',
      'Ear check',
    ],
    popular: false,
  },
  {
    icon: Brush,
    title: 'Express Groom',
    description: 'Quick touch-up for pets who need a fast refresh',
    duration: '45-60 min',
    price: 'From $35',
    features: ['Quick wash', 'Brush out', 'Nail trim', 'Sanitary trim', 'Face & feet cleanup'],
    popular: false,
  },
];

const additionalServices = [
  { name: 'Nail Painting', price: '$15' },
  { name: 'Teeth Cleaning', price: '$25' },
  { name: 'Flea Treatment', price: '$30' },
  { name: 'De-shedding Treatment', price: '$35' },
  { name: 'Aromatherapy Add-on', price: '$20' },
  { name: 'Premium Cologne', price: '$10' },
];
</script>

<template>
  <section
    id="services"
    class="py-20 bg-gradient-to-br from-accent to-orange-50 relative overflow-hidden"
  >
    <!-- Curved decorative elements -->
    <div class="absolute top-0 right-0 w-64 h-64 bg-primary/5 rounded-full blur-3xl"></div>
    <div class="absolute bottom-0 left-0 w-80 h-80 bg-secondary/5 rounded-full blur-3xl"></div>
    <div class="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 z-10">
      <!-- Header -->
      <div class="text-center mb-16">
        <h2 class="text-3xl lg:text-4xl font-bold text-foreground mb-4">Our Premium Services</h2>
        <p class="text-xl text-foreground/70 max-w-3xl mx-auto">
          From basic baths to full spa treatments, we offer everything your pet needs to look and
          feel their absolute best.
        </p>
      </div>

      <!-- Main Services -->
      <div class="grid md:grid-cols-2 lg:grid-cols-3 gap-8 mb-16">
        <Card
          v-for="(service, index) in mainServices"
          :key="index"
          class="relative group hover:shadow-xl transition-all duration-300 rounded-3xl border-2 hover:border-primary/20"
        >
          <Badge
            v-if="service.popular"
            class="absolute -top-3 left-6 bg-primary text-white rounded-full px-4 py-1"
          >
            Most Popular
          </Badge>

          <CardHeader class="text-center pb-4">
            <div
              class="w-16 h-16 bg-primary/10 rounded-3xl flex items-center justify-center mx-auto mb-4 group-hover:bg-primary/20 transition-colors"
            >
              <component :is="service.icon" class="text-primary" :size="32" />
            </div>
            <CardTitle class="text-xl mb-2">{{ service.title }}</CardTitle>
            <CardDescription class="text-foreground/70">
              {{ service.description }}
            </CardDescription>
          </CardHeader>

          <CardContent class="space-y-4">
            <div class="flex justify-between items-center">
              <div class="flex items-center gap-2">
                <Clock :size="16" class="text-primary/60" />
                <span class="text-sm text-foreground/60">{{ service.duration }}</span>
              </div>
              <span class="text-xl font-semibold text-primary">{{ service.price }}</span>
            </div>

            <div class="space-y-2">
              <h4 class="font-medium text-foreground">Includes:</h4>
              <ul class="space-y-1">
                <li
                  v-for="(feature, idx) in service.features"
                  :key="idx"
                  class="flex items-center gap-2 text-sm text-foreground/70"
                >
                  <div class="w-1.5 h-1.5 bg-primary rounded-full"></div>
                  {{ feature }}
                </li>
              </ul>
            </div>
          </CardContent>

          <CardFooter>
            <Button
              class="w-full rounded-full bg-primary hover:bg-primary/90 transition-colors py-6"
            >
              Book Now
              <ArrowRight :size="16" class="ml-2" />
            </Button>
          </CardFooter>
        </Card>
      </div>

      <!-- Additional Services -->
      <div class="bg-white rounded-3xl p-8 shadow-lg border-2 border-primary/10">
        <div class="text-center mb-8">
          <h3 class="text-2xl font-bold text-foreground mb-2">Additional Services</h3>
          <p class="text-foreground/70">
            Enhance your pet's grooming experience with our premium add-ons
          </p>
        </div>

        <div class="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
          <div
            v-for="(service, index) in additionalServices"
            :key="index"
            class="flex items-center justify-between p-4 border border-gray-200 rounded-lg hover:border-primary/30 transition-colors"
          >
            <div class="flex items-center gap-3">
              <Sparkles class="text-primary" :size="20" />
              <span class="font-medium text-foreground">{{ service.name }}</span>
            </div>
            <span class="font-semibold text-primary">{{ service.price }}</span>
          </div>
        </div>

        <div class="text-center mt-8">
          <Button variant="outline" size="lg">View All Services & Pricing</Button>
        </div>
      </div>
    </div>
  </section>
</template>
