// src/App.tsx
import Header from '@/components/Header';
import Hero from '@/components/landing/Hero';
import WhyUs from '@/components/landing/WhyUs';
import Services from '@/components/landing/Services';
import Packages from '@/components/landing/Packages';
import FAQ from '@/components/landing/FAQ';
import Footer from '@/components/landing/Footer';
import ScrollToTop from '@/components/ScrollToTop';
import { Toaster } from '@/components/ui/sonner';
export default function App() {
  return (
    <div className="min-h-screen">
      <Header />

      <main>
        <Hero />
        <WhyUs />
        <Services />
        <Packages />
        <FAQ />
      </main>
      <Footer />

      <ScrollToTop />
      <Toaster />
    </div>
  );
}

// src/App.vue
<script setup lang="ts">
import Header from './components/Header.vue';
import Hero from './components/Hero.vue';
import WhyUs from './components/WhyUs.vue';
import Services from './components/Services.vue';
import Packages from './components/Packages.vue';
import FAQ from './components/FAQ.vue';
import Footer from './components/Footer.vue';
import Testimonials from './components/Testimonials.vue';
</script>

<template>
  <div class="min-h-screen bg-background">
    <Header />
    <main>
      <Hero />
      <WhyUs />
      <Services />
      <Packages />
      <Testimonials />
      <FAQ />
    </main>
    <Footer />
  </div>
</template>
